---
- name: Homelab Setup 
  hosts: k3s_cluster
  #connection: local
  gather_facts: false
  become: true
  roles:
    - role: prereq
    - role: k3s
      become: true
      when: lookup('env', 'K3S_ENABLED') == 'true'
    - role: transmission
      when: lookup('env', 'TRANSMISSION_ENABLED') == 'true'

