---
- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Execute Helm install script
  ansible.builtin.command:
    cmd: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Verify Helm installation
  ansible.builtin.command:
    cmd: helm version
  register: helm_version
  changed_when: false

- name: Show Helm version
  ansible.builtin.debug:
    msg: "{{ helm_version.stdout }}"