---
- name: Install apt-transport-https, ca-certificates, and curl
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: yes  # Update the repository cache before the install
