---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    app: hello-world
    zone: prod
    version: v1
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 30000
        
        
      containers:        
        - name: nginx
          image: nginx:1.14.2
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
              add:
                - NET_BIND_SERVICE
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: hello-world

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-svc
#   labels:
#     app: hello-world
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     nodePort: 30001
#     protocol: TCP
#   selector:
#     app: hello-world

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-nginx-ingress
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: hello-svc
            port: 
              number: 80