---
- name: Homelab Setup 
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: k3s
      when: lookup('env', 'K3S_ENABLED') == 'true'
    - role: transmission
      when: lookup('env', 'TRANSMISSION_ENABLED') == 'true'
    - role: jackett
      when: lookup('env', 'JACKETT_ENABLED') == 'true'
    - role: radarr
      when: lookup('env', 'RADARR_ENABLED') == 'true'
    - role: sonarr
      when: lookup('env', 'SONARR_ENABLED') == 'true'
    

      

